# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hq6gRYFsZqi9aN1kR5gRZ7i6RiIrvP_i
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("zaheenhamidani/ultimate-spotify-tracks-db")

print("Path to dataset files:", path)

import pandas as pd
import os

data = pd.read_csv(os.path.join(path, "SpotifyFeatures.csv"))
print("Dataset Shape:", data.shape)
data.head()

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

# Define features if not already defined
features = ['danceability', 'energy', 'tempo', 'loudness', 'valence']

# Ensure X_scaled is defined
X = data[features]
X = X.dropna()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

inertia = []

K_range = range(1,11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(K_range, inertia, marker='o')
plt.title("Elbow Method for Optimal K")
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")
plt.show()

X = data[features]
X = X.dropna()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import matplotlib.pyplot as plt



plt.figure(figsize=(10,6))
data[features].hist(bins=20)
plt.suptitle("Feature Distribution")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))
sns.heatmap(data[features].corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation")
plt.show()

from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

import matplotlib.pyplot as plt


k=4
kmeans = KMeans(n_clusters=k, random_state=42)
kmeans.fit(X_scaled)
clusters = kmeans.labels_

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(8,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=clusters, cmap='viridis')
plt.title("Spotify Song Clusters (PCA)")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.colorbar(label="Cluster")
plt.show()

from sklearn.manifold import TSNE
sample = X_scaled[:5000]   # take only 5000 rows

tsne = TSNE(n_components=2, random_state=42)
X_tsne = tsne.fit_transform(sample)
# tsne = TSNE(n_components=2, random_state=42,init="pca")
# X_tsne = tsne.fit_transform(X_scaled)
plt.figure(figsize=(8,6))
plt.scatter(X_tsne[:,0], X_tsne[:,1], c=clusters[:5000], cmap='plasma')
plt.title("Spotify Song Clusters (t-SNE)")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.colorbar(label="Cluster")
plt.show()

data['Cluster'] = clusters
cluster_summary = data.groupby('Cluster')[features].mean()

print("\nCluster Characteristics:")
cluster_summary

data.to_csv("spotify_clustered_songs.csv", index=False)

print("Clustering completed and results saved.")

for i in range(4):
    print("\nCluster", i)
    print(data[data["Cluster"] == i][["track_name","artist_name"]].head(5))

